### ISSUE TITLE
Missing docker image for v0.4.8 in ghcr.io

### ISSUE THREAD

**Issue by BlacCello** [justwatchcom/sql_exporter#102]
The docker image for the newest release is currently missing in the Github Docker registry. Could you please provide the image there?

```
❯ docker pull ghcr.io/justwatchcom/sql_exporter:v0.4.8
Error response from daemon: manifest unknown

❯ docker pull ghcr.io/justwatchcom/sql_exporter:v0.4.7
v0.4.7: Pulling from justwatchcom/sql_exporter
Digest: sha256:167f9816c5d9a9abec050a527ee03e366626a86948b9af989b14e672a09c79c5
Status: Image is up to date for ghcr.io/justwatchcom/sql_exporter:v0.4.7
ghcr.io/justwatchcom/sql_exporter:v0.4.7
```

**Comment by dewey** [comment]
Hey, looks like something went wrong with the tagging there after switching to dockerx for multi platform images. I'm taking a look, thanks for reporting.

**Comment by dewey** [comment]
@BlacCello This has been fixed now, I had to tag a new release to pull in the latest Docker builder changes, so if you are requesting v0.4.9 you'll get the latest image now.
