### ISSUE TITLE
Missing MSSQL Integration Example

### ISSUE THREAD

**Issue by cr-Tair** [justwatchcom/sql_exporter#108]
While using the open-source SQL exporter, I noticed that there is no example provided for integrating with MSSQL, despite MSSQL being used in the exporter. This omission makes it difficult for users to set up MSSQL integrations effectively.

In order to find the connection string that needs to be used, I went to the library of MSSQL and found the documention:
`sqlserver://username:password@host/instance?param1=value&param2=value`

I suggest adding a dedicated example or documentation section specifically focused on setting up MSSQL integration within the exporter (and all other integrations that are not documented). 

Thank you!

**Comment by ilantnt** [comment]
Hi @dewey, I've submitted a PR that add the documentation of MSSQL connection string - 
https://github.com/justwatchcom/sql_exporter/pull/109
