### ISSUE TITLE
Possible to calculate query time taken?

### ISSUE THREAD

**Issue by jmreicha** [justwatchcom/sql_exporter#110]
I'm testing out the exporter and it is working for me so far. Wondering if there is any method to get the amount of time a query as a Prometheus metric so that I can measure certain database latencies.

Apologies if this is already outlined in docs, I might have missed it!

**Comment by dewey** [comment]
Hey, are you talking about getting the historic duration a query takes? If you can query it from the database you can do it, it won't be super accurate as you'd only get the value at the time Prometheus scrapes but might be good enough. In Postgres the pg_stat_activity table is probably your best bet.
