### ISSUE TITLE
Need to connect mysql database

### ISSUE THREAD

**Issue by manzajohn** [justwatchcom/sql_exporter#123]
I need to connect to one of my mysql database running as kubernetes pod. Where can i find the configurations for mysql? i see only Postgres configurations in the repository. Any guidance on  connecting mysql database will be appreciated

**Comment by dewey** [comment]
Any connection string that can be parsed by https://github.com/go-sql-driver/mysql would work.

**Comment by dewey** [comment]
The configuration file is just an example on what's possible, you'll have to define what you want in there.
