### ISSUE TITLE
use automaxprocs?

### ISSUE THREAD

**Issue by sebhoss** [justwatchcom/sql_exporter#137]
We are deploying sql_exporter into kubernetes and are currently setting GOMAXPROCS manually. If this package would use https://github.com/uber-go/automaxprocs we could remove that env var and simply set resource limits on the deployment.

**Comment by dewey** [comment]
Good point, would you be able to open a PR for that addition?

**Comment by sebhoss** [comment]
yep created https://github.com/justwatchcom/sql_exporter/pull/138

**Comment by dewey** [comment]
Perfect, thank you!
