### ISSUE TITLE
Grafana graphs not populating

### ISSUE THREAD

**Issue by Globegitter** [justwatchcom/sql_exporter#16]
I am using your k8s examples and managing to get the sql-exporter to show up in prometheus targets, but for some reason nothing is populatin in grafan. Looking at the metrics endpoint of the container I can see it is showing output. I am using the new prometheus 2.0.0 beta but not sure if it is in any way related to that, as I have other graphs showing up fine. Anything that I could have been missing?

**Comment by dominikschulz** [comment]
That sounds more than a general Prometheus question.

Real short:

1. Is the `/metrics` endpoint showing any metrics?
2. Is the Exporter showing up as a Target on the Prometheus Target page?
3. Is the datasource properly configured in Grafana?
4. Do the Queries used in the Grafana dashboard work in the Prometheus `/graph` view?

If that doesn't help please try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/prometheus) with the tag `prometheus`.

**Comment by Globegitter** [comment]
Yes to 1-4 (I do have other prometheus graphs populating in grafana), but I suppose it is just something with the grafana config then and will get to the bottom of it - thanks for the quick reply in any case.

**Comment by Globegitter** [comment]
It was indeed grafa, as we run the db on aws rather than within kubernetes.
