### ISSUE TITLE
Feature Request: Detecting failed scrapes

### ISSUE THREAD

**Issue by pierluca** [justwatchcom/sql_exporter#19]
I'm working on application where we're using SQL exporter to get a valuable metric for our use case: the time elapsed since a user inserted some data in a database table. It's very straightforward and we really liked the exporter !

However, when the database goes down (as part of our tests), I noticed that the metrics are "stuck". The sql_exporter keeps reporting that the queries failed, but the metrics are still present.

I think that continuing to reporting the last value is good (coherent with the overall Prometheus philosophy), but it would be great to have a boolean metric indicating failures and execution time.
Something similar to what is done by both mysqld_exporter and postgres_exporter.

They have two metrics:
* pg/mysqld_exporter_last_scrape_error
* pg/mysqld_exporter_last_scrape_duration_seconds

We would really like to have something similar with sql_exporter, such as:
`sql_exporter_last_scrape_failed{database="my_database", driver="postgres", query="my_query_name",... } := (True/False)`

What do you think it'd take to get there?

Thanks in advance for your help and any pointers you may provide.

**Comment by dominikschulz** [comment]
Thank you very much for the feedback and the suggestion.
That sounds like a very reasonable and useful addition.
I'll look into this in the next days.

**Comment by pierluca** [comment]
Sorry, I had made a copy-paste mistake. The second metric is:
pg/mysqld_exporter_last_scrape_duration_seconds

(I've edited my feature request above)

**Comment by sinkingpoint** [comment]
@dominikschulz Any progress here (I'm aware it's the holiday season :) ) ? This would also be a useful feature for us in detecting the health of our dbs

**Comment by dominikschulz** [comment]
@sinkingpoint Thanks for the reminder. I've created a PR which should cover this use case, but I'm not able to give it much exposure. So if someone could grab it and test if it works as expected, that'd be great.
