### ISSUE TITLE
MySQL documentation | "err":"default addr for network 'mysql:3306' unknown"

### ISSUE THREAD

**Issue by gree-gorey** [justwatchcom/sql_exporter#28]
The dsn for mysql driver should be defined this way:
```
'mysql://root:pass@(mysql:3306)/'
```
**Note** the parentheses and the trailing slash -- without it you will receive an error:
```
"err":"default addr for network 'mysql:3306' unknown"
```

Took me quite a time to debug it..

**Comment by pwilken** [comment]
You made my day, thank you so much.

**Comment by marthjod** [comment]
Thanks, but not an sql_exporter issue. DSN format options for the MySQL driver are documented [here](https://github.com/go-sql-driver/mysql#dsn-data-source-name).

**Comment by 15086479010lgd** [comment]
thanks a lot
