### ISSUE TITLE
How to edit /metrics page.

### ISSUE THREAD

**Issue by micline** [justwatchcom/sql_exporter#29]
When I entered metrics page, I saw many values about duration, memory and so on. And some metrics related with queries in config.yaml was located in end of page. But I want to see only metrics related with these queries. So can you tell me how to edit document in metrics page?

**Comment by marthjod** [comment]
sql_exporter includes metrics from Go and the promhttp library, so these are displayed as well. This is normal /metrics page behavior. You can't and shouldn't really edit that, plus the /metrics response is primarily intended for the Prometheus scraper.
