### ISSUE TITLE
Requesting to add Vertica driver support

### ISSUE THREAD

**Issue by bentzimortaboola** [justwatchcom/sql_exporter#43]
Hi

I added Vertica driver suppor locally and tests are in progress.
Only have to do to put under vendor/github the vertica go driver
Will be great to be part of the exporter

Thank you

**Comment by dewey** [comment]
We just merged a PR that adds this, please give it a shot and open a new issue if it does not work as expected.

**Comment by dewey** [comment]
This was now implemented by @lukas-mi in this PR: https://github.com/justwatchcom/sql_exporter/pull/45
