### ISSUE TITLE
How can I pass connection using env?

### ISSUE THREAD

**Issue by s-titov** [justwatchcom/sql_exporter#49]
Hello, thank for your exporter. 

How can I pass connection using env variables? 
I don't wanna show my connection's data in config.

**Comment by erlendvollset** [comment]
I tried setting `postgres://` (which is valid https://www.postgresql.org/docs/current/libpq-connect.html) as connection string and then setting the `PGHOST`, `PGDATABASE`, `PGUSER`, `PGPASSWORD` environment variables. But getting the following error in sql_exporter: `missing "=" after "postgres:" in connection info string`

**Comment by dewey** [comment]
I just added a feature that I've been using internally for a while already: https://github.com/justwatchcom/sql_exporter/pull/56

This should take care of this.
