### ISSUE TITLE
Panic: not implemented errors with MSSQL (Azure Managed Instance)

### ISSUE THREAD

**Issue by gk-mevers** [justwatchcom/sql_exporter#60]
We are experiencing panic: not implemented errors (and a subsequent crash of the exporter) when using it with an Azure Managed Instance MSSQL database. We have had success with other Azure-hosted MSSQL databases before, but the only difference is that the managed instance forces encrypted traffic which could be the cause of the issue. We have attempted changing the github.com/denisenkom/go-mssqldb dependency to a higher version but this unfortunately does not fix the issue.

Here's a stack trace of such an error happening:
```
panic: Not implemented

goroutine 45 [running]:
github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
	/src/vendor/github.com/denisenkom/go-mssqldb/net.go:167
crypto/tls.(*Conn).SetWriteDeadline(...)
	/usr/local/go/src/crypto/tls/conn.go:151
crypto/tls.(*Conn).closeNotify(0xc000910700)
	/usr/local/go/src/crypto/tls/conn.go:1361 +0xdb
crypto/tls.(*Conn).Close(0xc0000cadb8)
	/usr/local/go/src/crypto/tls/conn.go:1331 +0x69
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc0000cadd0)
	/src/vendor/github.com/denisenkom/go-mssqldb/mssql.go:361 +0x28
database/sql.(*driverConn).finalClose.func2()
	/usr/local/go/src/database/sql/sql.go:646 +0x3c
database/sql.withLock({0x12eb6e8, 0xc000629e60}, 0xc0000cae88)
	/usr/local/go/src/database/sql/sql.go:3396 +0x8c
database/sql.(*driverConn).finalClose(0xc000629e60)
	/usr/local/go/src/database/sql/sql.go:644 +0x117
```

**Comment by dewey** [comment]
Looks like this is an upstream issue from the library you are using, there's an open issue there: https://github.com/denisenkom/go-mssqldb/issues/688

I'd suggest to bring it up there, once this is fixed we can update the dependencies on our end.

**Comment by gk-mevers** [comment]
Yes, but the upstream issue was supposedly fixed in [deniseenkom/go-mssqldb/releases/tag/v0.10.0](https://github.com/denisenkom/go-mssqldb/releases/tag/v0.10.0) (at least for Go 1.16. I have tested it with that dependency, but it still does not seem to work. 

However, if I build with Go 1.15, the issue is resolved. Apparently it has to do with the addition of a [default write deadline in Conn.Close in Go 1.16](https://go.dev/doc/go1.16#crypto/tls).

**Comment by gk-mevers** [comment]
I tested this again today with denisenkom/go-mssqldb v0.12.2 and it still comes up with the same issue. I'm going to test with loglevel debug and see if I can get more context on the error.

**Comment by gk-mevers** [comment]
@dewey I managed to fix the issue and opened a PR.
