### ISSUE TITLE
Connection properties is not working without password

### ISSUE THREAD

**Issue by nivGandhi** [justwatchcom/sql_exporter#67]
Hello Team,

I have configured the below connection in config map but it is not working:-

      connections:
      - 'postgres://postgres_exporter@servername/postgres?sslmode=disable'
      
if I pass the password properties, it is working.

      connections:
      - 'postgres://postgres_exporter:**password**@servername/postgres?sslmode=disable'  

I have configured the secret and given correct password but it is not working.
 
Please suggest.

is there any way to configure multiple server connection in different config map?

**Comment by dewey** [comment]
Are you using the placeholders to inject environment variables into the connection string? See: https://github.com/justwatchcom/sql_exporter/pull/56

**Comment by nivGandhi** [comment]
> Are you using the placeholders to inject environment variables into the connection string? See: #56

No, I am directly passing the username and password in connections properties.

**Comment by nivGandhi** [comment]
> Are you using the placeholders to inject environment variables into the connection string? See: #56

HI,

It is working now using placeholders.

Thanks for your time and reply.
