### ISSUE TITLE
exporter has a lot of default metrics 

### ISSUE THREAD

**Issue by weiya1990** [justwatchcom/sql_exporter#69]
for example：go_gc_pauses_seconds_total_bucket  go_sched_latencies_seconds_bucket
![image](https://user-images.githubusercontent.com/38902618/180678917-5974c9c9-a235-4ba1-8605-81ea0a02ba4f.png)
![image](https://user-images.githubusercontent.com/38902618/180678958-59c5e521-a6fc-4bf5-96d2-f2c2b7edc1c0.png)

**Comment by gk-mevers** [comment]
Those are default Go metrics I believe.
If there are any time series you don't want to ingest/scrape, use a metric relabel with **drop** action.
Check here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
